---
# tasks file for v98765_vm_single

- include: preinstall.yml
  tags:
    - vmagent_install
    - vmagent_configure
    - vmagent_run

- include: install.yml
  tags:
    - vmagent_install

- include: configure.yml
  tags:
    - vmagent_configure

- name: ensure vmagent service is started and enabled
  systemd:
    daemon_reload: true
    name: vmagent
    state: started
    enabled: true
  tags:
    - vmagent_run
